### ISSUE TITLE
Allow to define custom package manager commands

### ISSUE THREAD

**Issue by ia3andy** [quarkiverse/quarkus-quinoa#134]
### Discussed in https://github.com/quarkiverse/quarkus-quinoa/discussions/133

<div type='discussions-op-text'>

<sup>Originally posted by **ia3andy** July  4, 2022</sup>
This discussion has been initiated by @computerlove in https://github.com/quarkiverse/quarkus-quinoa/pull/132.

I've been thinking into improving the customization of package manager commands in the long run (and not just "install").
I believe it would be nice to have something close to the script section in the package.json. e.g.:
```yaml
quarkus:
  quinoa:
     package-manager-command:
       install-frozen: "npm ci --cache $CACHE_DIR/.npm --prefer-offline"
       // install: npm install (would still be the default)
       build-prod: "npm build-prod"
       build-dev: "npm build-dev"
       dev: "BROWSER=OFF npm dev" // default is "BROWSER=NONE npm start"

```

Instead of just the argument it would allow to edit the entire command (including envs) for one or more the available "actions". If not set if would keep the default (what we currently have).

To allow this, we might need to use something like [commons.apache.org/proper/commons-exec](https://commons.apache.org/proper/commons-exec/) and be careful about os compat.

Any thoughts? 
</div>
