### ISSUE TITLE
Static Resource Paths Aren't URL Encoded In Route Handler

### ISSUE THREAD

**Issue by alex-lmco** [quarkiverse/quarkus-quinoa#481]
### Describe the bug

When serving assets with spaces in their name, they get redirected back to the SPA index.html page instead of being served up. This appears to be because the assets in the browser are URL encoded and the static handler is not URL encoding the file names and therefore saying it "doesn't handle it".

Example: URL for an asset is http://orchestrator.default.127.0.0.1.sslip.io:8080/assets/Destiny%20Logo.png, gets redirected back to index.html
Example: URL for an asset (no space), http://orchestrator.default.127.0.0.1.sslip.io:8080/assets/destinylogo.png gets served up just fine.

Quinoa recognizes the asset:

Quinoa is scanning directory: /linux-repos/orchestrator/src/main/webui/src
Quinoa is scanning directory: /linux-repos/orchestrator/src/main/webui/src/assets
Quinoa is watching: /linux-repos/orchestrator/src/main/webui/src/assets/Destiny Logo.png
Quinoa is watching: /linux-repos/orchestrator/src/main/webui/src/assets/destinylogo.png

Quinoa copies it to the build directory just fine:

![image](https://github.com/quarkiverse/quarkus-quinoa/assets/60933340/882a22d9-e59a-40e5-a491-758d46680845)

### Quinoa version

2.0.8

### Quarkus version

3.2.2.Final

### Build / Runtime

Angular

### Package Manager

NPM

### Steps to reproduce the behavior

1. Create a Quinoa Angular app and put a static asset with spaces in the name in src/main/webui/src/assets/
2. Create an angular app which serves up the image, e.g. `<h1 class="mat-h1"><img src="/assets/Destiny Logo.png" alt="Destiny Logo" height="50pt"></h1>`
3. Run `./gradlew quarkusDev`, notice that it works just fine because `ng serve` is watching the files with URL encoded file names for the route handler
4. Run `./gradlew clean quarkusBuild -Dquarkus.knative.deploy=true` and go to the deployed instance, notice that the file isn't displayed due to a redirection back to index.html
5. Change file to not have spaces and repeat 3 & 4 but this time Step 4 shows the image.

### Expected behavior

Static assets with spaces in their name are served up properly.

**Comment by melloware** [comment]
Good catch.  Definitely gotta be a bug.

**Comment by melloware** [comment]
@alex-lmco did you research where the bug is occurring in the code?

**Comment by alex-lmco** [comment]
@melloware I did not beyond looking at Quinoa seemingly using a Static Handler for it [here](https://github.com/quarkiverse/quarkus-quinoa/blob/main/runtime/src/main/java/io/quarkiverse/quinoa/QuinoaUIResourceHandler.java#L58).  I don't know the internals of Quinoa or Quarkus too well and wrote the issue here.  I don't know if it's actually a Quarkus bug under the hood.

**Comment by melloware** [comment]
Can you also post your application.properties settings for Quinoa as well?

**Comment by alex-lmco** [comment]
Here you go, I included all the http, vertx, and resteasy reactive properties too since they're kinda relevant.

```
quarkus:
  http:
    enable-compression: true
    cors:
      ~: true
      origins: /.*/
# snip
  vertx:
    prefer-native-transport: true
  resteasy-reactive:
    path: /api/
  quinoa:
    enable-spa-routing: true
    package-manager-command:
      build-env:
        NODE_ENV: development
"%dev":
  quarkus:
    http:
      port: 3000
"%prod":
  quarkus:
    quinoa:
      package-manager-command:
        build-env:
          NODE_ENV: production
# snip
```
